# Generated by Django 5.0.6 on 2024-05-25 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(default=0, max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999.99)])),
                ('years_of_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('company_url', models.URLField(blank=True, null=True)),
                ('applied_by', models.ManyToManyField(blank=True, null=True, related_name='applied_jobs', to='user.useraccount')),
                ('posted_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('education', models.CharField(choices=[('high_school', 'High School'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctorate', 'Doctorate')], max_length=20)),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='applied_user', to='user.useraccount')),
                ('job', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
