# Generated by Django 5.0.6 on 2024-05-23 08:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        ("user", "0002_delete_award_delete_certification_delete_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="application_date",
        ),
        migrations.RemoveField(
            model_name="job",
            name="applied_users",
        ),
        migrations.RemoveField(
            model_name="job",
            name="company",
        ),
        migrations.RemoveField(
            model_name="job",
            name="company_link",
        ),
        migrations.RemoveField(
            model_name="job",
            name="posted_user",
        ),
        migrations.AddField(
            model_name="application",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="job",
            name="posted_by",
            field=models.ForeignKey(
                default="wezza",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="user.useraccount",
            ),
        ),
    ]
