# Generated by Django 5.0.6 on 2024-05-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='applied_users',
            new_name='applied_by',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='posted_by_id',
            new_name='posted_by',
        ),
    ]
