# Generated by Django 5.2.3 on 2025-06-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_by',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to='user.useraccount'),
        ),
    ]
