# Generated by Django 5.0.6 on 2024-05-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_remove_application_application_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="date",
        ),
    ]
