# Generated by Django 5.0.6 on 2024-05-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_applied_users_job_applied_by_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='applied_jobs', to='user.useraccount'),
        ),
    ]
