# Generated by Django 5.0.6 on 2024-05-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_applied_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="applied_by",
        ),
    ]
