# Generated by Django 3.2.8 on 2024-05-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_created_at_job_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='comany',
            new_name='company',
        ),
    ]
