# Generated by Django 5.0.6 on 2024-05-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_application_user_alter_job_applied_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applied_users',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_user',
        ),
    ]
