# Generated by Django 5.0.6 on 2024-05-22 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_job_applied_users_remove_job_posted_user'),
        ('user', '0002_remove_useraccount_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useraccount'),
        ),
    ]
