# Generated by Django 5.0.6 on 2024-05-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
