# Generated by Django 5.0.6 on 2024-05-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=150)),
                ('user_type', models.CharField(choices=[
                 ('user', 'User'), ('admin', 'Admin')], max_length=50)),
                ('company_name', models.CharField(
                    blank=True, max_length=150, null=True)),
            ],
        ),
    ]
