# Generated by Django 5.2.3 on 2025-06-14 14:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exper',
            name='user_account',
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['-date_received']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_year']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-level', 'name']},
        ),
        migrations.RemoveField(
            model_name='award',
            name='date',
        ),
        migrations.RemoveField(
            model_name='award',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='award',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end',
        ),
        migrations.RemoveField(
            model_name='education',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start',
        ),
        migrations.RemoveField(
            model_name='education',
            name='type',
        ),
        migrations.RemoveField(
            model_name='license',
            name='when',
        ),
        migrations.RemoveField(
            model_name='license',
            name='where',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='purpose',
        ),
        migrations.AddField(
            model_name='award',
            name='date_received',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='award',
            name='issuing_organization',
            field=models.CharField(db_index=True, default='Issuing Organization', max_length=200),
        ),
        migrations.AddField(
            model_name='award',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_type',
            field=models.CharField(choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('certificate', 'Certificate'), ('bootcamp', 'Bootcamp')], default='bachelor', max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(default='Institution Name', max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.CharField(default='2020', max_length=4),
        ),
        migrations.AddField(
            model_name='license',
            name='credential_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='license',
            name='credential_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='license',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='license',
            name='issuing_organization',
            field=models.CharField(default='Issuing Organization', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Project description'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(db_index=True, default='Award Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='award',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='user.useraccount'),
        ),
        migrations.AlterField(
            model_name='education',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='user.useraccount'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='title',
            field=models.CharField(db_index=True, default='Interest Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='license',
            name='title',
            field=models.CharField(default='License Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='license',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='user.useraccount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user.useraccount'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, default='Skill Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type_job',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer')], default='job_seeker', max_length=20),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certificate Title', max_length=200)),
                ('issuing_organization', models.CharField(default='Issuing Organization', max_length=200)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, default='', max_length=100)),
                ('credential_url', models.URLField(blank=True, default='')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='user.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='Company Name', max_length=200)),
                ('position', models.CharField(default='Position Title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='user.useraccount')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.DeleteModel(
            name='Cert',
        ),
        migrations.DeleteModel(
            name='Exper',
        ),
    ]
