# Generated by Django 5.0.6 on 2024-05-23 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exper',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
