# Generated by Django 6.0 on 2025-12-29 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jobs', '0002_alter_job_applied_by'),
        ('app_core_users', '0002_alter_education_start_alter_license_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_user', to='app_core_users.useraccount'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_jobs.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core_users.useraccount'),
        ),
    ]
