# Generated by Django 6.0 on 2025-12-29 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='when',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
